
name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Use the version your app requires

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install -f

    # Step 4: Build the app (if you have a build step; skip if not needed)
    - name: Build the app
      run: npm run build --if-present

    # Step 5: Deploy to Azure App Service
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: celescontainerwebapp # Your App Service name
        slot-name: testing
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Set this secret in GitHub

